### ISSUE TITLE
Discrepancy with output of nlmeans.py

### ISSUE THREAD

**Issue by riddhishb** [nipy/dipy#1011]
I am working on adaptive denoising patch for dipy, and I noticed an interesting catch in the current implementation of nlmeans.py. I have discussed this with @Garyfallidis 

Following is the output with p=1,b=1 (3x3 block_size and 3x3 patch_size)
![1](https://cloud.githubusercontent.com/assets/7941975/13995710/5af19ef0-f150-11e5-8a73-952523f1b95c.png)

Following is the output with p=3,b=3 (7x7 block_size and 7x7 patch_size)
![2](https://cloud.githubusercontent.com/assets/7941975/13995751/8d5859c4-f150-11e5-8527-86c35d000c03.png)

and the error map between the above two images is 
![3](https://cloud.githubusercontent.com/assets/7941975/13995829/f8f8d96a-f150-11e5-9adb-ee9e83440ebd.png)

Ideally as per the equations (given below) the output should get more smooth on choosing the larger block/patch sizes (if we refer to [this](http://scil.dinf.usherbrooke.ca/wp-content/papers/descoteaux-etal-miccai08.pdf) or [[coupe2008]](http://www.ncbi.nlm.nih.gov/pubmed/18390341)), but that is not the case. (in fact there is no blockwise approach of averaging in denspeed.pyx)

equation 1 (here B is the block size and V is the Patch size)
<img width="298" alt="screen shot 2016-03-24 at 12 41 15 am" src="https://cloud.githubusercontent.com/assets/7941975/13997677/31829db8-f159-11e5-92c6-f509ea72e9df.png">

equation 2
<img width="248" alt="screen shot 2016-03-24 at 12 41 25 am" src="https://cloud.githubusercontent.com/assets/7941975/13997697/4dd70e5e-f159-11e5-8207-68e42adb2b2c.png">

In fact for all cases where patch_size = block_size we get the same output!

I have been working to solve this bug and will make a PR soon with some changes in denspeed.pyx file. I would like to know your comments on the same.

**Comment by arokem** [comment]
Just to be clear: is the output identical in these two cases?

**Comment by grlee77** [comment]
@riddhishb

One might reasonably expect that perhaps the "block size" means that the the central pixel of the patch would traverse a region equal to the block size, but that is not what the code actually does.

If you look at the function `process_block` in denspeed.pyx, the patch is only looped over the locations in the block where no pixels in the patch extend beyond the block edges.  So if the block size matches the patch size, the central patch of the block is only compared to itself!
In your first example above,  within `process_block`, `P = 3`, `BS=2*3+1=7`, so the loops in `process_block` are `for range(3, 4): ` which means only a single location is considered!

I would recommended raising an error if the block radius is not strictly greater than the patch radius, otherwise, no denoising is actually being done.

**Comment by riddhishb** [comment]
@grlee77  Exactly, I was about to comment that. 
@arokem Not just these cases, as @grlee77 mentioned, for all the cases where patch_radius >= block_radius we get no denoising.

**Comment by riddhishb** [comment]
@arokem @Garyfallidis I think we can close this issue now.

**Comment by arokem** [comment]
Closed through #1018
