### ISSUE TITLE
Reconstruction FOD

### ISSUE THREAD

**Issue by benalayaines** [nipy/dipy#1044]
Hi,
I'm Ines BEN ALAYA , i'm a PhD student and i'm working with diffusion MRI.
I intend  to estimate the FOD from a signal that has been generated using a multi-tensor model ,i download the file reconst_csd.py.
Can i reconstrutct the FOD using the diffusion signal and the response function (i don't have the diffusion weighted images).
I will be grateful if you can help me.
Best regards.

**Comment by arokem** [comment]
Yes. You can do that by replacing these lines: 

https://github.com/nipy/dipy/blob/master/doc/examples/reconst_csd.py#L25-L30

with lines that assign your simulated signal into `data` and create a gradient table that matches the gradient table that was used in your simulation into `gtab`. 

You will also need to have a response function, instead of the response function estimated here: 

https://github.com/nipy/dipy/blob/master/doc/examples/reconst_csd.py#L48

But if you simulated this yourself, you should know what the values for that are, because they correspond to the values used in each tensor element in the signal that was generated by your simulation.

**Comment by benalayaines** [comment]
Thank you very much for the quick reply.
I don't understand the last sentense,  we have to use the same tensor used in the signal generation in each voxel , Is it right? 
I used this code to generate the response function
a = FA/sqrt(3-2*FA^2);
D = 0.75*[ 1-a 0 0; 0 1-a 0; 0 0 1+2*a ];
I will use the data of challenge ISBI'12 , in which the values of lambda change from one voxel to another. we have to estimate the response function for each voxel?

**Comment by arokem** [comment]
I think this means you want to set: 

    response = ((1 + 2*a, 1-a, 1-a), S0)

Where S0 is the mean non-diffusion weighted signal used to generate the simulation.

**Comment by benalayaines** [comment]
Hi,
Could you help me to modify the code (reconst_csd.py) in order  to estimate the FOD in individual voxels?? 
i have the diffusion signal (vector 65*1) and the response function?
Many thanks for considering my request.

**Comment by jchoude** [comment]
Is this question answered? Can we close?

**Comment by benalayaines** [comment]
yes you can close this discussion.Thank you very much.
    Le mercredi 4 octobre 2017 à 20:20:06 UTC+1, Jean-Christophe Houde <notifications@github.com> a écrit :  
 
 
Is this question answered? Can we close?
