### ISSUE TITLE
Installation instructions for windows need to be updated

### ISSUE THREAD

**Issue by Garyfallidis** [nipy/dipy#1146]
To say that you need to have visual studio together with anaconda to make everything work. Except if you use the dipy conda binaries. @arokem we need to add pytables on that conda right?

**Comment by Garyfallidis** [comment]
Also we need to check if sklearn is available in anaconda by default and put a note for cvxopt (that is not available) but there is a work around. Using conda install -c clg_boar cvxopt

**Comment by arokem** [comment]
You don't need Visual Studio if you install from conda forge. That's the whole idea - it gets compiled for you on Appveyor (assuming that works...).

It looks like `cvxopt` is also available through conda-forge: https://github.com/conda-forge/cvxopt-feedstock, so that's not a problem either.

As for whether some package (e.g. scikit-learn) is installed per default: I think it doesn't matter. Conda installs all the dependencies specified in the recipe, so it doesn't matter whether sklearn, cvxopt or any other dependency is already installed on the user's machine when they install dipy. The dependencies *should* get automatically installed. 

For the time being, added cvxopt, pytables to the dependencies: https://github.com/conda-forge/dipy-feedstock/pull/6

**Comment by Garyfallidis** [comment]
Yes, I agree. But we can put something for the people developing. That they need visual studio.

**Comment by arokem** [comment]
How's this?

https://github.com/nipy/dipy/pull/1052/commits/96c2e4126f84313d014626e642303887e78c3cca

**Comment by skoudoro** [comment]
closed by #1361
