### ISSUE TITLE
Need of a travis bot that runs ana/mini/conda and vtk=7.1.0+

### ISSUE THREAD

**Issue by Garyfallidis** [nipy/dipy#1296]
Hi all,

All our travis bots right now use debian packaging mechanisms and pypi. But people are constantly moving into using Anaconda for scientific computing in python.

Can we setup one of our travis bots to install miniconda? If yes that would be helpful in general and for the visualization tests.

So far trying to run viz tests and make them compatible from VTK 5, 6 and 7 has been extremely difficult.
Also VTK has made huge changes from 5, to 6 and 7 and has changed its backend moving to OpenGL2 which gives big advantages. For example, shading programming, better volumetric renderers and new support for headless rendering.

So, I suggest to change our strategy with vtk in a similar way we did for cython. For cython we decided to upgrade often our minimum dependencies. I think we should do the same for VTK. 

However, we may have issues in non-conda systems. For example in debian/ubuntu even in Ubuntu 17.04 which is recent they still provide by default VTK 5.10. 
 
There is no need for rushed decisions but having a bot that actually uses conda and recent versions of vtk would be very helpful for debugging.

Let me know what you think.

**Comment by yarikoptic** [comment]
Sure thing you could and probably should also setup travis to install some conda! ;)  you could look into https://github.com/nipy/nipype/blob/master/.travis.yml on how to accomplish it

As for VTK -- if you want dipy be easily usable on some previous releases of debian and ubuntu, you might want to retain some compatibility with older VTKs.  FWIW as far as I see it we do have vtk6 in recent debian/ubuntus (as well as vtk5):
```shell
$> whohas --strict -D Debian,Ubuntu libvtk5-dev
Ubuntu      libvtk5-dev                            5.8.0-14.1ubuntu3  2M              all                       http://packages.ubuntu.com/trusty/libvtk5-dev
Ubuntu      libvtk5-dev                            5.10.1+dfsg-2.1bui 2M              all                       http://packages.ubuntu.com/xenial/libvtk5-dev
Debian      libvtk5-dev                            5.8.0-13+b1        3M              all                       http://packages.debian.org/wheezy/libvtk5-dev
Debian      libvtk5-dev                            5.8.0-17.5+b1      2M              all                       http://packages.debian.org/jessie/libvtk5-dev
Debian      libvtk5-dev                            5.8.0-17.4                         all                       http://packages.debian.org/sid/libvtk5-dev
2 25839.....................................:Fri 07 Jul 2017 05:43:22 PM EDT:.
hopa:~
$> whohas --strict -D Debian,Ubuntu libvtk6-dev
Ubuntu      libvtk6-dev                            6.0.0-6            4M              all                       http://packages.ubuntu.com/trusty/libvtk6-dev
Ubuntu      libvtk6-dev                            6.2.0+dfsg1-10buil 2M              all                       http://packages.ubuntu.com/xenial/libvtk6-dev
Ubuntu      libvtk6-dev                            6.3.0+dfsg1-1build 2M              all                       http://packages.ubuntu.com/yakkety/libvtk6-dev
Ubuntu      libvtk6-dev                            6.3.0+dfsg1-3      2M              all                       http://packages.ubuntu.com/zesty/libvtk6-dev
Ubuntu      libvtk6-dev                            6.3.0+dfsg1-5      2M              all                       http://packages.ubuntu.com/artful/libvtk6-dev
Debian      libvtk6-dev                            6.1.0+dfsg2-6      6M              all                       http://packages.debian.org/jessie/libvtk6-dev
Debian      libvtk6-dev                            6.3.0+dfsg1-5      2M              all                       http://packages.debian.org/stretch/libvtk6-dev
Debian      libvtk6-dev                            6.3.0+dfsg1-5      2M              all                       http://packages.debian.org/buster/libvtk6-dev
Debian      libvtk6-dev                            6.3.0+dfsg1-9      2M              all                       http://packages.debian.org/sid/libvtk6-dev
```

**Comment by arokem** [comment]
One random thought: I think that we should start considering whether
dipy.viz deserves to be its own library, developed side-by-side with dipy.

A few reasons: different set of dependencies. We might still want to
support use of dipy for analysis on some previous releases, while not
supporting visualization on these platforms, so that we can run ahead here
with this.

Testing on travis will also become easier. Our tests already take hours to
run, and if we add more machines here it will make running these tests even
longer.

On Fri, Jul 7, 2017 at 2:44 PM, Yaroslav Halchenko <notifications@github.com

**Comment by Garyfallidis** [comment]
Hi @arokem, the tests are not affected currently by the viz. These do not take time at all. 

I am currently, not persuaded that dipy.viz needs to be its own library at this stage however I do see that as a good future direction when the API starts maturing and becoming more generic and solid.

Now, if you think that this separation should happen before 1.0 you may want to start drafting a short but explicit plan.

The plan should describe how the API, tutorials, website and support will be split. Also, what that will mean for testing. Will we need new buildbots, setup systems, conda packages etc? Will we need a new website too? Think also about namespaces. HR is very important. Will this separation reduce our HR needs or increase them? And user support. Will this need its own user support and community building efforts? If yes that will mean serious time involvement on our side. We may prefer to get some funding first. Finally, you need to think of citations. Currently someone using the viz modules will cite DIPY if we create a new project then we need a new paper for that project otherwise we lose citations and reduce the probability of being funded again.

**Comment by arokem** [comment]
I was thinking more along the lines of the kind of split that the Jupyter
project has among different repos: ipython, jupyter, nbconvert etc,

Each one of the separate repos has a separate test suite, allowing you to
test each sub-part separately. In a sense, dipy-viz is already an optional
dependency within dipy, because VTK is not required to run any of the rest
of Dipy. But we can keep the documentation (particularly the examples) as
they are now, with the addition of a dependency on this. This also makes
sense in terms of the software engineering, because it forces even clearer
modularity among these different components. However, the main benefit I
see for separating the two is that we will be able to release each package
separately (coordinated with each other, of course), making our release
cycles a bit easier. We can also manage the dependencies separately (along
the lines ), so that people who are on older versions. Finally, it
potentially expands the user base for the visualization tools to people who
are not as focused on diffusion MRI, but still want flexible configurable
visualization tools based on VTK (since our API is much more pleasant than
the VTK API...).

Re: testing time -- sure, the viz tests are not really the limiting factor
in terms of running the tests on a single machine, but the comment is with
regards to the original intent of this PR (setting up more travis bots). If
we need more bots with different combinations of installation method
(pip/conda) different Python versions, and with VTK on and off, the
combinatorics starts being a bit much.

I agree that software citation is a tricky issue, but I am not sure that we
have that figured out as it is. For example, people who have contributed to
Dipy since that paper came out are currently not getting credit for the
work they did. We might want to use a similar mechanism to that used by
Nipype, where users are encouraged to cite the software itself, rather than
a paper that no longer accurately represents the software (because the
software has developed further since the paper was written). See:
http://nipype.readthedocs.io/en/latest/about.html.

But sure: we don't have to hurry to do this. I think this is something we
should put on the list for 1.0 -- at least as an item for discussion.

**Comment by skoudoro** [comment]
I think we can close this issue since `dipy.viz` has its own library: [FURY](https://github.com/fury-gl/fury)
