### ISSUE TITLE
mapfit_laplacian_aniso (high non-Gaussianity, NG values in CSF)

### ISSUE THREAD

**Issue by maryamafzali** [nipy/dipy#1321]
Hi,

I used ‘mapfit_laplacian_aniso’ to extract MAP-MRI indices on HCP data. NG index should have small values in CSF compared to the WM. However, in my results CSF is not dark in NG map. Would you please help me to solve this problem?

Thank you,

Best regards,
Maryam

**Comment by maurozucchelli** [comment]
Hi Maryam, this can be proably due to the fact that the ventricles usually are more noisy with respect to the rest of the tissues. Try to:
- reduce the radial order of the basis to 4
- increase the regularization of the basis

What are your b-values? Consider also that after b=1000 the CSF signal basically disappears and only noise is left for MAPMRI to fit. Try to denoise your data a bit and see if the NG reduces after that.

Best,

Mauro

**Comment by maryamafzali** [comment]
Hi Mauro,

Thank you for the explanations. I will change the order and the regularization as you suggested. 
I use HCP data with b-values 1000, 2000 and 3000. 

Best,
Maryam
