### ISSUE TITLE
Could tests for functionality not supported on big endians just skip?

### ISSUE THREAD

**Issue by yarikoptic** [nipy/dipy#1587]
## Description
in debian on s390x we have a number of tests failing thus failing the entire build process:
https://buildd.debian.org/status/fetch.php?pkg=dipy&arch=s390x&ver=0.14.0-1&stamp=1526401155&raw=0
I wondered if you could
1. Move from `ValueError` to some dedicated `ArchitectureNotSupportedError` derived from `NotImplementedError` exception?
2. decorate such tests (or may be possible to adjust general runner?) so they would catch such exception and skip the test?

Cheers!

**Comment by arokem** [comment]
I don't have any objections to this. The decorator approach sounds the most straight-forward. Since it sounds like you have some specific implementation details in mind, would you mind putting in a PR for that?

**Comment by yarikoptic** [comment]
oh, I also didn't realize that it was the exception stemming all the way from Cython... will look in there too, and meanwhile will propose a PR here as well... hopefully ;-)

**Comment by emanuele** [comment]
Hi,

Even though I haven't contributed to the solution of this issue, I'd like to remind everyone that [Python2 will retire in 10 months](https://pythonclock.org/) and, at the moment, this issue is preventing DiPy to have a Python3 package in NeuroDebian. As far as I understand NeuroDebian is one of the main ways to distribute DiPy so many users will get in trouble before the end of this year.

If some of you has time and knowledge to fix this issue, it will be greatly appreciated.

**Comment by arokem** [comment]
Hey @yarikoptic :  sorry for the slowness here. Do you have any idea: how would we know that we are on a s390x machine? Is there something in the os module that can tell us that?

**Comment by yarikoptic** [comment]
I guess what matters is the endianness -- `sys.byteorder` to consult

```shell
yoh@zelenka:~$ uname -a
Linux zelenka 4.9.0-9-s390x #1 SMP Debian 4.9.168-1+deb9u3 (2019-06-16) s390x GNU/Linux

yoh@zelenka:~$ python -c 'import sys; print(sys.byteorder)'
big
```

**Comment by arokem** [comment]
Thanks @yarikoptic! 

@skoudoro : are you on it?

**Comment by skoudoro** [comment]
ok, on it!
