### ISSUE TITLE
Reminder to add in the docs that users will need to update nibabel to 2.3.0 during the next release

### ISSUE THREAD

**Issue by Garyfallidis** [nipy/dipy#1607]
This did it for me in anaconda
conda install -c conda-forge nibabel

**Comment by arokem** [comment]
Maybe we should add the contents of [this file](https://github.com/nipy/dipy/blob/master/requirements.txt) to somewhere in the documentation? Under a "dependencies" header?

**Comment by skoudoro** [comment]
Since it is already in our requirements file, I think the update will be automatic if they try to install the new version of DIPY (or master).  Indeed, my version of nibabel was automatically updated after a `pip install --user -e .`

For sure, it will be the same with conda. So, We just have to warn them.

**Comment by skoudoro** [comment]
You can find the content [here in the documentation](http://nipy.org/dipy/dependencies.html)  @arokem. It just needs to be updated

**Comment by arokem** [comment]
Ah yes. Let's update that file!

**Comment by arokem** [comment]
Closed through #1609
