### ISSUE TITLE
Upgrade Scipy for MIX framework?

### ISSUE THREAD

**Issue by ShreyasFadnavis** [nipy/dipy#1727]
## Description
- Cython Special in New version of Scipy. 
- May need to upgrade Cython version

**Comment by skoudoro** [comment]
Which scipy version? Which function is currently missing on our current scipy minimum version?

**Comment by arokem** [comment]
It's failing because you are requiring cvxpy:

https://travis-ci.org/nipy/dipy/jobs/484124382#L3279

You need to write something like this, to conditionally import cvxpy, if it
is installed:

https://github.com/nipy/dipy/blob/master/dipy/reconst/mapmri.py#L22

And then test only if cvxpy is installed:

https://github.com/nipy/dipy/blob/master/dipy/reconst/tests/test_mapmri.py#L623

**Comment by ShreyasFadnavis** [comment]
@arokem thank you so much for this!
