### ISSUE TITLE
Figure out how to get a "used by" button

### ISSUE THREAD

**Issue by arokem** [nipy/dipy#1856]
For some reason, Fury has this button: 

<img width="149" alt="Screen Shot 2019-06-12 at 4 38 53 PM" src="https://user-images.githubusercontent.com/118582/59360558-99375e00-8d30-11e9-97e8-227ef2ddeb5c.png">

But dipy does not. My theory is that this has to do with the metadata on PYPI, or some-such. We need to figure this out and get our button up here as well.

**Comment by jhlegarreta** [comment]
@arokem Interesting.

Inspecting fury's [dependency graph](https://github.com/fury-gl/fury/network/dependencies), it is weird that the **dipy repository it seems to depend on is not nipy**'s one, but one under the [mohini organization](https://github.com/mohini/dipy). Sounds weird at least.

Oddly enough, the `mohini/dipy` **does have a *used-by* label, with 105 repositories using it**... 

Even @richford 's [afq-insight-paper repository](https://github.com/richford/afq-insight-paper/network/dependencies) (which is successfully listed in fury's dependents) uses the *mohini/dipy* instead of *nipy/dipy*. And I found many, many more examples.

So I definitely think that has something to do with it.

Apart from that, both dipy's and fury's `setup.py` seems to be similar, with at least a couple of fields that are not being correctly filled for dipy (`download_url` -there is nothing to download in the pointed url and `requires` should may be or be complemented with `install_requires`?)

**Comment by arokem** [comment]
Update: I wrote an email to GitHub support about this. Will update here when I hear back.

**Comment by skoudoro** [comment]
any news from github support?

**Comment by arokem** [comment]
None as of yet

**Comment by arokem** [comment]
Just heard back from GitHub support. 

This should now be up to date: https://github.com/nipy/dipy/network/dependents

And the "used by" button should also show up on our front page within 24 hours.

**Comment by arokem** [comment]
Let's keep this open until that happens, though.

**Comment by skoudoro** [comment]
That's a great news! 👍

**Comment by skoudoro** [comment]
the "used by" button show up already! cool! you can close this issue! 

Thank you @arokem for this! 

ps: I still wonder how they solve it...

**Comment by jhlegarreta** [comment]
Yes, it's already there :tada: Very nice. Thanks Ariel. Feeling curious like Serge, did they had to manually change it? Was it a bot? An inactive user? The user/fork are still there.

**Comment by arokem** [comment]
It looks like it required some manual configuration. I got an email from what I think was a person and it sounded like they had to do something on their end. I have no idea who that other user was and why they decided to designate that the upstream.
