### ISSUE TITLE
window.record() function shows the coronal view

### ISSUE THREAD

**Issue by luqily** [nipy/dipy#1901]
window.record() funtions always show the axial view of fiber orientation. So I want to know how can I show the coronal view of fiber orientation.

**Comment by jhlegarreta** [comment]
@luqily this is more a question having to do with [FURY](https://fury.gl/latest/index.html), which is the rendering tool used by DIPY.

In order to display an arbitrary orientation, you will need to set the appropriate angle for the camera in the [scene](https://github.com/fury-gl/fury/blob/1aed2cace52d0750036537e3eac663d3251548fb/fury/window.py#L24).

The [Visualize bundles and metrics on bundles example](https://fury.gl/latest/auto_examples/viz_bundles.html#sphx-glr-auto-examples-viz-bundles-py) may be of help in this task. You basically need to set the camera properties, using either the `set_camera` method or the elevation/azimuth angles.

Finally, may be maintainers could clarify where to post questions or ask for help by adding an appropriate section in the website and/or `README` file (note that the [community](https://fury.gl/latest/community/index.html) link gives a 404 error)? May be the [FURY mailing list](https://mail.python.org/mailman3/lists/fury.python.org/) would be more appropriate? @skoudoro @Garyfallidis ?

**Comment by luqily** [comment]
@jhlegarreta Thanks for your reply.
I would like to refer to the example [sfm_reconst.html](url), but it shows the axial view of fiber orientation by default. I want to change the axial view to the coronal view. 
So if I don't need to show the streamline, but just the fiber direction as in the example, do I still need to use FURY?

**Comment by jhlegarreta** [comment]
Yes.

**Comment by luqily** [comment]
@jhlegarreta Thanks a lot!
