### ISSUE TITLE
How can I get streamlines using fiber orientation by bedpostx of MRtrix3?

### ISSUE THREAD

**Issue by luqily** [nipy/dipy#1920]
I have got the fiber orientation files 'dyads<i>' by bedpostx of MRtrix3. Now I want to get streamlines using them. What should I do?

**Comment by Garyfallidis** [comment]
lol wrong github repo to ask this question. Still funny.

**Comment by RafaelNH** [comment]
@luqily - not sure if I get your question. Do you intend to produce streamlines using Dipy from files produced by MRtrix3? If that is the case - it might be possible to program a function to do that - but you really have to ask the MRtrix team to know how they save the fiber orientation in their files. Also, keep in mind that supporting compatibility with output files of other packages goes out of the scope of Dipy - what is why this issue was closed.
