### ISSUE TITLE
Customize at runtime the number of cores nlmeans is using

### ISSUE THREAD

**Issue by fmorency** [nipy/dipy#608]
This is a feature request to be able to customize at runtime the number of cores nlmeans is using.

**Use case**: We are running a dMRI pipeline on a massively parallel cluster and we need more control over the number of core each _task_ is using in order to be performance efficient.

**Comment by samuelstjean** [comment]
That would be in https://github.com/nipy/dipy/blob/master/dipy/denoise/denspeed.pyx line 84 for the records, we need to add a num_cores variable to the parallel function http://docs.cython.org/src/userguide/parallelism.html

Of course we'll also need to put a new variable to carry around the value, add a valid default and everything in between.

**Comment by fmorency** [comment]
Hey guys, I don't think this feature request has been fixed...

**Comment by arokem** [comment]
Oh yeah - you're right. Mind making a quick PR with the fix?

**Comment by samuelstjean** [comment]
We actually looked at it two weeks ago or so, and it involves playing with setup.py options to bind it with openmp. We also realized it does not work out of the box on a mac because the llvm version they use by default has no openmp support (and it also means that nothing is parallelized for these guys by default sadly). And well, it is fixable in the cython version, but the building and binding part to actualy use the option just made us give up in the end as the suggestion on the cython website itself was not working.

**Comment by jchoude** [comment]
Ok so just to correct what Sam is saying, it IS doable. We didn't do it for our internal codebase because it was not a priority, but it is true that it is more that juste 1 or 2 lines.

**Comment by Garyfallidis** [comment]
I am looking at it.

**Comment by skoudoro** [comment]
Should we close this one @Garyfallidis @fmorency  ?

**Comment by samuelstjean** [comment]
It was indeed fixed ages ago, new nlmeans is not parallel so it's probably also fine to close the issue anyway.
